-- Import Schools from LIST-OF-SCHOOL.xlsx
-- Generated: 2025-12-08T04:27:04.582Z
-- Total Schools: 816

-- Clear existing schools (optional - comment out if you want to keep existing data)
-- TRUNCATE TABLE schools CASCADE;

-- Insert schools
INSERT INTO schools (name, municipality, principal, created_at) VALUES
  ('Cotabato City Central Pilot School', 'Cotabato City', NULL, NOW()),
  ('Kimpo Elementary School', 'Cotabato City', NULL, NOW()),
  ('Krislamville ES', 'Cotabato City', NULL, NOW()),
  ('P.C. Hill Elementary School', 'Cotabato City', NULL, NOW()),
  ('Sero Central School', 'Cotabato City', NULL, NOW()),
  ('Buaya-Buaya Elementary School', 'Cotabato City', NULL, NOW()),
  ('Bubong Elementary School', 'Cotabato City', NULL, NOW()),
  ('Diocolano Elementary School', 'Cotabato City', NULL, NOW()),
  ('L.R. Sebastian ES', 'Cotabato City', NULL, NOW()),
  ('Mokamadali Elementary School', 'Cotabato City', NULL, NOW()),
  ('Notre Dame Village Central ES', 'Cotabato City', NULL, NOW()),
  ('Pagalamatan Elementary School', 'Cotabato City', NULL, NOW()),
  ('Tamontaka Central School', 'Cotabato City', NULL, NOW()),
  ('Timako Elementary School', 'Cotabato City', NULL, NOW()),
  ('Usman Baunga ES', 'Cotabato City', NULL, NOW()),
  ('Amirol ES', 'Cotabato City', NULL, NOW()),
  ('Darping ES', 'Cotabato City', NULL, NOW()),
  ('Datu Ayunan ES', 'Cotabato City', NULL, NOW()),
  ('Datu Usman Elementary School', 'Cotabato City', NULL, NOW()),
  ('Lugay-Lugay Central School', 'Cotabato City', NULL, NOW()),
  ('Rojas Central ES', 'Cotabato City', NULL, NOW()),
  ('Datu Siang Central School', 'Cotabato City', NULL, NOW()),
  ('Don E. Sero Elementary School', 'Cotabato City', NULL, NOW()),
  ('J. Marquez Elementary School', 'Cotabato City', NULL, NOW()),
  ('Vilo Central Elementary School', 'Cotabato City', NULL, NOW()),
  ('BANGSAMORO PUBLIC MADRASAH', 'Cotabato City', NULL, NOW()),
  ('Mandanas Elementary School', 'Cotabato City', NULL, NOW()),
  ('Fernanda Borbon Elementary School', 'Cotabato City', NULL, NOW()),
  ('CANIZARES NATIONAL HIGH SCHOOL- School of Arts and Trades', 'Cotabato City', NULL, NOW()),
  ('Cotabato City NHS - Rojas #13', 'Cotabato City', NULL, NOW()),
  ('Cotabato City NHS - Main', 'Cotabato City', NULL, NOW()),
  ('Datu Ayunan National High School', 'Cotabato City', NULL, NOW()),
  ('Datu Siang NHS', 'Cotabato City', NULL, NOW()),
  ('J. Marquez NHS', 'Cotabato City', NULL, NOW()),
  ('Notre Dame Village National High School', 'Cotabato City', NULL, NOW()),
  ('Pilot Provincial Science High School and Technology', 'Cotabato City', NULL, NOW()),
  ('CCNHS - Datu Sema Kalantungan Site', 'Cotabato City', NULL, NOW()),
  ('CCNHS - ANNEX ( Bubong Site)', 'Cotabato City', NULL, NOW()),
  ('CCNHS-ANNEX (Buaya-Buaya Site)', 'Cotabato City', NULL, NOW()),
  ('CCNHS - Annex (LR Sebastian Site)', 'Cotabato City', NULL, NOW()),
  ('CCNHS - Annex (Diocolano Site)', 'Cotabato City', NULL, NOW()),
  ('CCNHS - Annex (Don E. Sero Site)', 'Cotabato City', NULL, NOW()),
  ('CCNHS - Annex (PC Hill Site)', 'Cotabato City', NULL, NOW()),
  ('Cotabato City Bangsamoro Stand Alone Senior High School', 'Cotabato City', NULL, NOW()),
  ('Mohammad Integrated School', 'Cotabato City', NULL, NOW()),
  ('School Name', 'Cotabato City', NULL, NOW()),
  ('Maguindanao Childhood Development Center', 'Cotabato City', NULL, NOW()),
  ('Mamalimping ES', 'Cotabato City', NULL, NOW()),
  ('Sadangen PS', 'Cotabato City', NULL, NOW()),
  ('Salasal ES', 'Cotabato City', NULL, NOW()),
  ('Ayob ES', 'Cotabato City', NULL, NOW()),
  ('Campo Cuatro ES', 'Cotabato City', NULL, NOW()),
  ('Datu Dumpao Banog ES', 'Cotabato City', NULL, NOW()),
  ('Datu Sailila CES', 'Cotabato City', NULL, NOW()),
  ('Datu Sangki Ampatuan CES', 'Cotabato City', NULL, NOW()),
  ('Dimampao ES', 'Cotabato City', NULL, NOW()),
  ('Durian ES', 'Cotabato City', NULL, NOW()),
  ('Kamasi ES', 'Cotabato City', NULL, NOW()),
  ('Kauran ES', 'Cotabato City', NULL, NOW()),
  ('Kaya-Kaya ES', 'Cotabato City', NULL, NOW()),
  ('Madanding ES', 'Cotabato City', NULL, NOW()),
  ('Malatimon ES', 'Cotabato City', NULL, NOW()),
  ('Mao ES', 'Cotabato City', NULL, NOW()),
  ('Old Maganoy ES', 'Cotabato City', NULL, NOW()),
  ('Pinagayao ES', 'Cotabato City', NULL, NOW()),
  ('Saniag ES', 'Cotabato City', NULL, NOW()),
  ('Sugadol ES', 'Cotabato City', NULL, NOW()),
  ('Shariff Sherjan Sangki ES', 'Cotabato City', NULL, NOW()),
  ('Bai Bagongan Paglas ES', 'Cotabato City', NULL, NOW()),
  ('Daladagan ES', 'Cotabato City', NULL, NOW()),
  ('Datu Luminog Mangelen PES', 'Cotabato City', NULL, NOW()),
  ('Datu Yuseff Paglas ES', 'Cotabato City', NULL, NOW()),
  ('Kabuling ES', 'Cotabato City', NULL, NOW()),
  ('Kayaga ES', 'Cotabato City', NULL, NOW()),
  ('Kayupo ES', 'Cotabato City', NULL, NOW()),
  ('Malangit CES', 'Cotabato City', NULL, NOW()),
  ('Mamalinta ES', 'Cotabato City', NULL, NOW()),
  ('Maslabeng ES', 'Cotabato City', NULL, NOW()),
  ('Popol ES', 'Cotabato City', NULL, NOW()),
  ('Datu Idon S''pi ES', 'Cotabato City', NULL, NOW()),
  ('Talitay ES', 'Cotabato City', NULL, NOW()),
  ('Tumbao CES', 'Cotabato City', NULL, NOW()),
  ('Baguadatu ES', 'Cotabato City', NULL, NOW()),
  ('Bunawan ES', 'Cotabato City', NULL, NOW()),
  ('Datang ES', 'Cotabato City', NULL, NOW()),
  ('Datu Paglas CS', 'Cotabato City', NULL, NOW()),
  ('Gen. SKP Memorial ES', 'Cotabato City', NULL, NOW()),
  ('Kalumenga ES', 'Cotabato City', NULL, NOW()),
  ('Katil ES', 'Cotabato City', NULL, NOW()),
  ('Tocao - Madidis CES', 'Cotabato City', NULL, NOW()),
  ('Lipao ES', 'Cotabato City', NULL, NOW()),
  ('Malala ES', 'Cotabato City', NULL, NOW()),
  ('M. Adil CES', 'Cotabato City', NULL, NOW()),
  ('Napok ES', 'Cotabato City', NULL, NOW()),
  ('Palao sa Buto ES', 'Cotabato City', NULL, NOW()),
  ('Salendab ES', 'Cotabato City', NULL, NOW()),
  ('Sepaka ES', 'Cotabato City', NULL, NOW()),
  ('Alonganen ES', 'Cotabato City', NULL, NOW()),
  ('Ambadao ES', 'Cotabato City', NULL, NOW()),
  ('Balong ES', 'Cotabato City', NULL, NOW()),
  ('Dado ES', 'Cotabato City', NULL, NOW()),
  ('Damabalas ES', 'Cotabato City', NULL, NOW()),
  ('Dapiawan CES', 'Cotabato City', NULL, NOW()),
  ('Kabalukanen ES', 'Cotabato City', NULL, NOW()),
  ('Datu Gumbay Piang CES', 'Cotabato City', NULL, NOW()),
  ('Datu Pendililang Piang ES', 'Cotabato City', NULL, NOW()),
  ('Duaminanga ES', 'Cotabato City', NULL, NOW()),
  ('Ganta ES', 'Cotabato City', NULL, NOW()),
  ('Kalipapa ES', 'Cotabato City', NULL, NOW()),
  ('Kitango ES', 'Cotabato City', NULL, NOW()),
  ('Kitapok ES', 'Cotabato City', NULL, NOW()),
  ('Lintukan ES', 'Cotabato City', NULL, NOW()),
  ('Liong ES', 'Cotabato City', NULL, NOW()),
  ('Masigay ES', 'Cotabato City', NULL, NOW()),
  ('Montay ES', 'Cotabato City', NULL, NOW()),
  ('Pagatin ES', 'Cotabato City', NULL, NOW()),
  ('Sambulawan CES', 'Cotabato City', NULL, NOW()),
  ('Dimaukom ES', 'Cotabato City', NULL, NOW()),
  ('Iganagampong ES', 'Cotabato City', NULL, NOW()),
  ('Labulabu ES', 'Cotabato City', NULL, NOW()),
  ('Lapok ES', 'Cotabato City', NULL, NOW()),
  ('Limpongo ES', 'Cotabato City', NULL, NOW()),
  ('Datu Unsay CES', 'Cotabato City', NULL, NOW()),
  ('Nabundas CES', 'Cotabato City', NULL, NOW()),
  ('Pamalian ES', 'Cotabato City', NULL, NOW()),
  ('Pikeg ES', 'Cotabato City', NULL, NOW()),
  ('Shariff Aguak CES', 'Cotabato City', NULL, NOW()),
  ('Satan ES', 'Cotabato City', NULL, NOW()),
  ('Timbangan ES', 'Cotabato City', NULL, NOW()),
  ('Toron ES', 'Cotabato City', NULL, NOW()),
  ('Batungkayo ES', 'Cotabato City', NULL, NOW()),
  ('Bulit ES', 'Cotabato City', NULL, NOW()),
  ('Limbalud ES', 'Cotabato City', NULL, NOW()),
  ('Lower Baguinged ES', 'Cotabato City', NULL, NOW()),
  ('Maridagao ES', 'Cotabato City', NULL, NOW()),
  ('Matalam Farm Settlement ES', 'Cotabato City', NULL, NOW()),
  ('Pagagawan ES', 'Cotabato City', NULL, NOW()),
  ('Datu Montawal CES', 'Cotabato City', NULL, NOW()),
  ('Balungis ES', 'Cotabato City', NULL, NOW()),
  ('Baya ES', 'Cotabato City', NULL, NOW()),
  ('Buliok ES', 'Cotabato City', NULL, NOW()),
  ('Dalgan ES', 'Cotabato City', NULL, NOW()),
  ('Damalasak ES', 'Cotabato City', NULL, NOW()),
  ('Datu Alimot ES', 'Cotabato City', NULL, NOW()),
  ('Kalbugan ES', 'Cotabato City', NULL, NOW()),
  ('Kilangan ES', 'Cotabato City', NULL, NOW()),
  ('Mamasabulod ES', 'Cotabato City', NULL, NOW()),
  ('Linandangan ES', 'Cotabato City', NULL, NOW()),
  ('Datu Udtog Matalam Jr MES', 'Cotabato City', NULL, NOW()),
  ('Sapakan ES', 'Cotabato City', NULL, NOW()),
  ('Bai Malaida M. Pendatun CES', 'Cotabato City', NULL, NOW()),
  ('Damakling ES', 'Cotabato City', NULL, NOW()),
  ('Digaon ES', 'Cotabato City', NULL, NOW()),
  ('Paglala Memorial ES', 'Cotabato City', NULL, NOW()),
  ('Datu Salipada Khaled Pendatun Jr. ES', 'Cotabato City', NULL, NOW()),
  ('Lasangan ES', 'Cotabato City', NULL, NOW()),
  ('Midconding ES', 'Cotabato City', NULL, NOW()),
  ('Mibpandacan ES', 'Cotabato City', NULL, NOW()),
  ('Paglat CES', 'Cotabato City', NULL, NOW()),
  ('Panosolen ES', 'Cotabato City', NULL, NOW()),
  ('Campo ES', 'Cotabato City', NULL, NOW()),
  ('Tunggol ES', 'Cotabato City', NULL, NOW()),
  ('Datu Tahir Ampatuan CES', 'Cotabato City', NULL, NOW()),
  ('Gumbay ES', 'Cotabato City', NULL, NOW()),
  ('Libutan ES', 'Cotabato City', NULL, NOW()),
  ('Tukanalipao ES', 'Cotabato City', NULL, NOW()),
  ('Lusay ES', 'Cotabato City', NULL, NOW()),
  ('Mamasapano CES', 'Cotabato City', NULL, NOW()),
  ('Pidsandawan ES', 'Cotabato City', NULL, NOW()),
  ('Angkayamat ES', 'Cotabato City', NULL, NOW()),
  ('Bakat ES', 'Cotabato City', NULL, NOW()),
  ('Barurao CES', 'Cotabato City', NULL, NOW()),
  ('Bulod ES', 'Cotabato City', NULL, NOW()),
  ('Dansalan ES', 'Cotabato City', NULL, NOW()),
  ('Darampua ES', 'Cotabato City', NULL, NOW()),
  ('Gadungan ES', 'Cotabato City', NULL, NOW()),
  ('Kulambog ES', 'Cotabato City', NULL, NOW()),
  ('Malibpolok ES', 'Cotabato City', NULL, NOW()),
  ('Mileb ES', 'Cotabato City', NULL, NOW()),
  ('Paldong ES', 'Cotabato City', NULL, NOW()),
  ('Datu Tecson Mamalo ES', 'Cotabato City', NULL, NOW()),
  ('Pidsalenggian ES', 'Cotabato City', NULL, NOW()),
  ('Pidsandawan ES', 'Cotabato City', NULL, NOW()),
  ('Sambolawan ES', 'Cotabato City', NULL, NOW()),
  ('Sampao ES', 'Cotabato City', NULL, NOW()),
  ('Sapakan CES', 'Cotabato City', NULL, NOW()),
  ('Bagan ES', 'Cotabato City', NULL, NOW()),
  ('Bai Salud Sultan ES', 'Cotabato City', NULL, NOW()),
  ('Kalantungan ES', 'Cotabato City', NULL, NOW()),
  ('Kalumamis ES', 'Cotabato City', NULL, NOW()),
  ('Datu Kasim ES', 'Cotabato City', NULL, NOW()),
  ('Macasampen ES', 'Cotabato City', NULL, NOW()),
  ('Midtimbang CES', 'Cotabato City', NULL, NOW()),
  ('Muslim ES', 'Cotabato City', NULL, NOW()),
  ('Tambunan CES', 'Cotabato City', NULL, NOW()),
  ('Alimao ES', 'Cotabato City', NULL, NOW()),
  ('Kiteb CES', 'Cotabato City', NULL, NOW()),
  ('Adaon ES', 'Cotabato City', NULL, NOW()),
  ('Nunangan ES', 'Cotabato City', NULL, NOW()),
  ('Bahar ES', 'Cotabato City', NULL, NOW()),
  ('Binaton ES', 'Cotabato City', NULL, NOW()),
  ('Bongo ES', 'Cotabato City', NULL, NOW()),
  ('Brawarbatew ES', 'Cotabato City', NULL, NOW()),
  ('Buludan ES', 'Cotabato City', NULL, NOW()),
  ('Lumao ES', 'Cotabato City', NULL, NOW()),
  ('Itaw ES', 'Cotabato City', NULL, NOW()),
  ('Kaus ES', 'Cotabato City', NULL, NOW()),
  ('Kigan ES', 'Cotabato City', NULL, NOW()),
  ('Kinemkem ES', 'Cotabato City', NULL, NOW()),
  ('Kitol ES', 'Cotabato City', NULL, NOW()),
  ('Kuhan ES', 'Cotabato City', NULL, NOW()),
  ('Kuya ES', 'Cotabato City', NULL, NOW()),
  ('Lamud ES', 'Cotabato City', NULL, NOW()),
  ('Lete ES', 'Cotabato City', NULL, NOW()),
  ('Letingan ES', 'Cotabato City', NULL, NOW()),
  ('Looy ES', 'Cotabato City', NULL, NOW()),
  ('Mafran ES', 'Cotabato City', NULL, NOW()),
  ('Pelagio P. Platon ES', 'Cotabato City', NULL, NOW()),
  ('Aliman B. Gunsi ES', 'Cotabato City', NULL, NOW()),
  ('Pilar ES', 'Cotabato City', NULL, NOW()),
  ('Refra ES', 'Cotabato City', NULL, NOW()),
  ('Benuan ES', 'Cotabato City', NULL, NOW()),
  ('Hadji Usop T. Campong ES', 'Cotabato City', NULL, NOW()),
  ('San Jose ES', 'Cotabato City', NULL, NOW()),
  ('Sanduagan ES', 'Cotabato City', NULL, NOW()),
  ('Eliseo C. Sioson Sr. ES', 'Cotabato City', NULL, NOW()),
  ('Timanan CES', 'Cotabato City', NULL, NOW()),
  ('Trecero ES', 'Cotabato City', NULL, NOW()),
  ('Dimananal ES', 'Cotabato City', NULL, NOW()),
  ('Datu Sumapal ES', 'Cotabato City', NULL, NOW()),
  ('Datu Bandala Mamasabulod ES', 'Cotabato City', NULL, NOW()),
  ('Tukanalugong ES', 'Cotabato City', NULL, NOW()),
  ('Muti ES', 'Cotabato City', NULL, NOW()),
  ('Fukol PS', 'Cotabato City', NULL, NOW()),
  ('Lanting PS', 'Cotabato City', NULL, NOW()),
  ('Guinibon ES', 'Cotabato City', NULL, NOW()),
  ('Pidsimbulan ES', 'Cotabato City', NULL, NOW()),
  ('Datu Powa K. Mangudadatu ES', 'Cotabato City', NULL, NOW()),
  ('Balanaken ES', 'Cotabato City', NULL, NOW()),
  ('Elian PS', 'Cotabato City', NULL, NOW()),
  ('Reina Regente ES', 'Cotabato City', NULL, NOW()),
  ('Kyamko ES', 'Cotabato City', NULL, NOW()),
  ('Maitumaig ES', 'Cotabato City', NULL, NOW()),
  ('Tukanakuden ES', 'Cotabato City', NULL, NOW()),
  ('Ahan ES', 'Cotabato City', NULL, NOW()),
  ('Tamar ES', 'Cotabato City', NULL, NOW()),
  ('Feta ES', 'Cotabato City', NULL, NOW()),
  ('Upper Idtig ES', 'Cotabato City', NULL, NOW()),
  ('Matagabong ES', 'Cotabato City', NULL, NOW()),
  ('Upak ES', 'Cotabato City', NULL, NOW()),
  ('South Binangga ES', 'Cotabato City', NULL, NOW()),
  ('Mangelen Andang ES', 'Cotabato City', NULL, NOW()),
  ('Bulod ES', 'Cotabato City', NULL, NOW()),
  ('Tugal ES', 'Cotabato City', NULL, NOW()),
  ('Baital ES', 'Cotabato City', NULL, NOW()),
  ('Inug-ug ES', 'Cotabato City', NULL, NOW()),
  ('Dataya ES', 'Cotabato City', NULL, NOW()),
  ('Datu Langalen Matagmama ES', 'Cotabato City', NULL, NOW()),
  ('Mangadeg ES', 'Cotabato City', NULL, NOW()),
  ('Biarong ES', 'Cotabato City', NULL, NOW()),
  ('Tuka ES', 'Cotabato City', NULL, NOW()),
  ('Maringen ES', 'Cotabato City', NULL, NOW()),
  ('Mari ES', 'Cotabato City', NULL, NOW()),
  ('Sultan Umpig ES', 'Cotabato City', NULL, NOW()),
  ('Kalian ES', 'Cotabato City', NULL, NOW()),
  ('Kalim ES', 'Cotabato City', NULL, NOW()),
  ('Ambolinog ES', 'Cotabato City', NULL, NOW()),
  ('Sinalayan ES', 'Cotabato City', NULL, NOW()),
  ('Gaunan ES', 'Cotabato City', NULL, NOW()),
  ('Kakal ES', 'Cotabato City', NULL, NOW()),
  ('Salam ES', 'Cotabato City', NULL, NOW()),
  ('Limba Ampatuan ES', 'Cotabato City', NULL, NOW()),
  ('Penditen ES', 'Cotabato City', NULL, NOW()),
  ('Linamunan Alikan Kalipa ES', 'Cotabato City', NULL, NOW()),
  ('Guintawan ES', 'Cotabato City', NULL, NOW()),
  ('Talapas ES', 'Cotabato City', NULL, NOW()),
  ('Kanguan E. Uy CES', 'Cotabato City', NULL, NOW()),
  ('Butilen ES', 'Cotabato City', NULL, NOW()),
  ('Hadji Salik Kalaing ES', 'Cotabato City', NULL, NOW()),
  ('Tulaguey Sambren ES', 'Cotabato City', NULL, NOW()),
  ('Upper D''lag ES', 'Cotabato City', NULL, NOW()),
  ('Sumakubay ES', 'Cotabato City', NULL, NOW()),
  ('Ramcor ES', 'Cotabato City', NULL, NOW()),
  ('Langgapanan ES', 'Cotabato City', NULL, NOW()),
  ('Datu Alamansa Angas ES', 'Cotabato City', NULL, NOW()),
  ('Lower Siling ES', 'Cotabato City', NULL, NOW()),
  ('Filasol PS', 'Cotabato City', NULL, NOW()),
  ('Datu Koguia Utto ES', 'Cotabato City', NULL, NOW()),
  ('Datu Conte Mangelen ES', 'Cotabato City', NULL, NOW()),
  ('Kaladturan ES', 'Cotabato City', NULL, NOW()),
  ('Fabian Marcos ES', 'Cotabato City', NULL, NOW()),
  ('Masdar ES', 'Cotabato City', NULL, NOW()),
  ('Tual ES', 'Cotabato City', NULL, NOW()),
  ('Assemb. Mama Masukat, Sr. ES', 'Cotabato City', NULL, NOW()),
  ('Pimbalakan ES', 'Cotabato City', NULL, NOW()),
  ('Tatak ES', 'Cotabato City', NULL, NOW()),
  ('Gagadanan ES', 'Cotabato City', NULL, NOW()),
  ('Datu Hoffer Ampatuan CES', 'Cotabato City', NULL, NOW()),
  ('Datu Aliman Ampatuan ES', 'Cotabato City', NULL, NOW()),
  ('Langkuno ES', 'Cotabato City', NULL, NOW()),
  ('Kulasi ES', 'Cotabato City', NULL, NOW()),
  ('Embing Mama ES', 'Cotabato City', NULL, NOW()),
  ('Datu Anggal Midtimbang ES', 'Cotabato City', NULL, NOW()),
  ('Omar PS', 'Cotabato City', NULL, NOW()),
  ('Datu Pinagayao Ampatuan ES', 'Cotabato City', NULL, NOW()),
  ('Mangumpig Alon ES', 'Cotabato City', NULL, NOW()),
  ('Bulod ES', 'Cotabato City', NULL, NOW()),
  ('Katitisan ES', 'Cotabato City', NULL, NOW()),
  ('Angkokoy ES', 'Cotabato City', NULL, NOW()),
  ('Naco ES', 'Cotabato City', NULL, NOW()),
  ('Andavit ES', 'Cotabato City', NULL, NOW()),
  ('Ganoy ES', 'Cotabato City', NULL, NOW()),
  ('Pandi Elementary School', 'Cotabato City', NULL, NOW()),
  ('Tee ES', 'Cotabato City', NULL, NOW()),
  ('Dimaukom Utto ES', 'Cotabato City', NULL, NOW()),
  ('Gawang Elementary School', 'Cotabato City', NULL, NOW()),
  ('Utto-Andao ES', 'Cotabato City', NULL, NOW()),
  ('Upper Bagoinged ES', 'Cotabato City', NULL, NOW()),
  ('Makalag PS', 'Cotabato City', NULL, NOW()),
  ('Balugo ES', 'Cotabato City', NULL, NOW()),
  ('Macatabang Memorial ES', 'Cotabato City', NULL, NOW()),
  ('Mao ES', 'Cotabato City', NULL, NOW()),
  ('Sugadol ES', 'Cotabato City', NULL, NOW()),
  ('Datu Abdulkadil O. Matalam Sr. ES', 'Cotabato City', NULL, NOW()),
  ('Datu Bunta ES', 'Cotabato City', NULL, NOW()),
  ('Kitedted ES', 'Cotabato City', NULL, NOW()),
  ('Timuay Tata Amuba ES', 'Cotabato City', NULL, NOW()),
  ('Tuladan L. Masandil ES', 'Cotabato City', NULL, NOW()),
  ('Tumbaga ES', 'Cotabato City', NULL, NOW()),
  ('North Binangga ES', 'Cotabato City', NULL, NOW()),
  ('Ampatuan NHS', 'Cotabato City', NULL, NOW()),
  ('Balungis NHS', 'Cotabato City', NULL, NOW()),
  ('Buliok NHS', 'Cotabato City', NULL, NOW()),
  ('Datu Paglas NHS', 'Cotabato City', NULL, NOW()),
  ('Datu Piang NHS', 'Cotabato City', NULL, NOW()),
  ('Datu Udtog Matalam Sr. MNHS', 'Cotabato City', NULL, NOW()),
  ('Gen. Salipada K. Pendatun NHS', 'Cotabato City', NULL, NOW()),
  ('Paglat NHS', 'Cotabato City', NULL, NOW()),
  ('Kauran NHS', 'Cotabato City', NULL, NOW()),
  ('Maguindanao NHS', 'Cotabato City', NULL, NOW()),
  ('South Upi NHS', 'Cotabato City', NULL, NOW()),
  ('Rajah Buayan NHS', 'Cotabato City', NULL, NOW()),
  ('Mamasapano NHS', 'Cotabato City', NULL, NOW()),
  ('Talayan NHS', 'Cotabato City', NULL, NOW()),
  ('Tunggol NHS', 'Cotabato City', NULL, NOW()),
  ('Bai Maguinal E.Langalen MNHS', 'Cotabato City', NULL, NOW()),
  ('Datu Anggal Midtimbang MNHS', 'Cotabato City', NULL, NOW()),
  ('Datu Samad Ukas NHS', 'Cotabato City', NULL, NOW()),
  ('Kaslon Sinalanganan NHS', 'Cotabato City', NULL, NOW()),
  ('Saga A. Nangkong NHS', 'Cotabato City', NULL, NOW()),
  ('Kaya-kaya NHS', 'Cotabato City', NULL, NOW()),
  ('Nunangan NHS', 'Cotabato City', NULL, NOW()),
  ('Datu Kasim NHS', 'Cotabato City', NULL, NOW()),
  ('Bulod NHS', 'Cotabato City', NULL, NOW()),
  ('Datu Mamalo Memorial NHS', 'Cotabato City', NULL, NOW()),
  ('Buluan NHS', 'Cotabato City', NULL, NOW()),
  ('Kilangan NHS', 'Cotabato City', NULL, NOW()),
  ('Zapakan NHS', 'Cotabato City', NULL, NOW()),
  ('Datu Tahir Ampatuan NHS', 'Cotabato City', NULL, NOW()),
  ('Datu Sailila NHS', 'Cotabato City', NULL, NOW()),
  ('Dimaukom NHS', 'Cotabato City', NULL, NOW()),
  ('Campo NHS', 'Cotabato City', NULL, NOW()),
  ('Hadji Datu Abubakar K. Pendatun NHS', 'Cotabato City', NULL, NOW()),
  ('Guindulungan NHS', 'Cotabato City', NULL, NOW()),
  ('Datu Saudi Uy Ampatuan MNHS', 'Cotabato City', NULL, NOW()),
  ('Kabalukanen NHS', 'Cotabato City', NULL, NOW()),
  ('Datu Abdula M. Camino MNHS', 'Cotabato City', NULL, NOW()),
  ('Datu Unsay NHS', 'Cotabato City', NULL, NOW()),
  ('Bai Tembabay NHS', 'Cotabato City', NULL, NOW()),
  ('Lumao NHS', 'Cotabato City', NULL, NOW()),
  ('Pandan NHS', 'Cotabato City', NULL, NOW()),
  ('Manindolo NHS', 'Cotabato City', NULL, NOW()),
  ('Katong Madidis NHS', 'Cotabato City', NULL, NOW()),
  ('Mangudadatu NHS', 'Cotabato City', NULL, NOW()),
  ('Maulana NHS', 'Cotabato City', NULL, NOW()),
  ('Pandag NHS', 'Cotabato City', NULL, NOW()),
  ('Looy Integrated Technical Vocational NHS', 'Cotabato City', NULL, NOW()),
  ('Pilar Integrated Technical Voc. NHS', 'Cotabato City', NULL, NOW()),
  ('Limpongo NHS', 'Cotabato City', NULL, NOW()),
  ('Hadji Salik Kalaing NHS', 'Cotabato City', NULL, NOW()),
  ('TOMICOR INTEGRATED SCHOOL', 'Cotabato City', NULL, NOW()),
  ('MADIA INTEGRATED SCHOOL', 'Cotabato City', NULL, NOW()),
  ('SCHOOL NAME', 'Cotabato City', NULL, NOW()),
  ('Barongisan Primary School', 'Cotabato City', NULL, NOW()),
  ('Abubacar Siddique ES', 'Cotabato City', NULL, NOW()),
  ('Barira CES', 'Cotabato City', NULL, NOW()),
  ('Bualan ES', 'Cotabato City', NULL, NOW()),
  ('Datu Mantani Taug Memorial ES', 'Cotabato City', NULL, NOW()),
  ('Gadung ES', 'Cotabato City', NULL, NOW()),
  ('Gubat Memorial Elementary School', 'Cotabato City', NULL, NOW()),
  ('Ibra Bulyoc Memo Central ES', 'Cotabato City', NULL, NOW()),
  ('Korosuyan ES', 'Cotabato City', NULL, NOW()),
  ('Lipa ES', 'Cotabato City', NULL, NOW()),
  ('Macarimbang ES', 'Cotabato City', NULL, NOW()),
  ('Manalao PS', 'Cotabato City', NULL, NOW()),
  ('MOROG- MAMALAKAT CENTRAL ELEM.SCHOOL', 'Cotabato City', NULL, NOW()),
  ('Nabalawag ES', 'Cotabato City', NULL, NOW()),
  ('Nate-Umpar PS', 'Cotabato City', NULL, NOW()),
  ('Palangka PS', 'Cotabato City', NULL, NOW()),
  ('Ruminimbang Elementary School', 'Cotabato City', NULL, NOW()),
  ('Sumesid ES', 'Cotabato City', NULL, NOW()),
  ('Tantangan ES', 'Cotabato City', NULL, NOW()),
  ('Tomawis Memo ES', 'Cotabato City', NULL, NOW()),
  ('Aratuc Elementary School', 'Cotabato City', NULL, NOW()),
  ('Baguiangen ES', 'Cotabato City', NULL, NOW()),
  ('Buldon CES', 'Cotabato City', NULL, NOW()),
  ('Central Edcor ES', 'Cotabato City', NULL, NOW()),
  ('Dinganen Central ES', 'Cotabato City', NULL, NOW()),
  ('Edbul ES', 'Cotabato City', NULL, NOW()),
  ('Karim ES', 'Cotabato City', NULL, NOW()),
  ('Kulimpang ES', 'Cotabato City', NULL, NOW()),
  ('Lower Dinganen ES', 'Cotabato City', NULL, NOW()),
  ('Makalian ES', 'Cotabato City', NULL, NOW()),
  ('Mataya Elem', 'Cotabato City', NULL, NOW()),
  ('Minabay E/S', 'Cotabato City', NULL, NOW()),
  ('Nuyo Elementary School', 'Cotabato City', NULL, NOW()),
  ('Piers PS', 'Cotabato City', NULL, NOW()),
  ('Potri Dabaleig ES', 'Cotabato City', NULL, NOW()),
  ('Raranaon ES', 'Cotabato City', NULL, NOW()),
  ('Rumidas PS', 'Cotabato City', NULL, NOW()),
  ('Tambak PS', 'Cotabato City', NULL, NOW()),
  ('Awang ES', 'Cotabato City', NULL, NOW()),
  ('Bitu ES', 'Cotabato City', NULL, NOW()),
  ('Broce CES', 'Cotabato City', NULL, NOW()),
  ('Camp Siongco ES', 'Cotabato City', NULL, NOW()),
  ('Capiton ES', 'Cotabato City', NULL, NOW()),
  ('Datu Candido Andong ES', 'Cotabato City', NULL, NOW()),
  ('Datu Wampa Baraguir Elementary School', 'Cotabato City', NULL, NOW()),
  ('Dimapatoy PS', 'Cotabato City', NULL, NOW()),
  ('Dinaig ES', 'Cotabato City', NULL, NOW()),
  ('Don A. Martinez ES', 'Cotabato City', NULL, NOW()),
  ('Kusiong ES', 'Cotabato City', NULL, NOW()),
  ('Labungan ES', 'Cotabato City', NULL, NOW()),
  ('Lasdan PS', 'Cotabato City', NULL, NOW()),
  ('Lim ES', 'Cotabato City', NULL, NOW()),
  ('Linek ES', 'Cotabato City', NULL, NOW()),
  ('Margues ES', 'Cotabato City', NULL, NOW()),
  ('Mompong Elementary School', 'Cotabato City', NULL, NOW()),
  ('Nabilan PS', 'Cotabato City', NULL, NOW()),
  ('Paningusan ES', 'Cotabato City', NULL, NOW()),
  ('Tanuel ES', 'Cotabato City', NULL, NOW()),
  ('Tapian ES', 'Cotabato City', NULL, NOW()),
  ('Taviran Elementary School', 'Cotabato City', NULL, NOW()),
  ('Tenorio ES', 'Cotabato City', NULL, NOW()),
  ('Ambolodto ES', 'Cotabato City', NULL, NOW()),
  ('Bagoenged ES', 'Cotabato City', NULL, NOW()),
  ('Datu Pinguiaman ES', 'Cotabato City', NULL, NOW()),
  ('Benolen ES', 'Cotabato City', NULL, NOW()),
  ('Bugawas ES', 'Cotabato City', NULL, NOW()),
  ('Datu Kiram ES', 'Cotabato City', NULL, NOW()),
  ('Dalican Pilot ES', 'Cotabato City', NULL, NOW()),
  ('Kinebeka ES', 'Cotabato City', NULL, NOW()),
  ('Kurintem ES', 'Cotabato City', NULL, NOW()),
  ('Neketan ES', 'Cotabato City', NULL, NOW()),
  ('Sifaran ES', 'Cotabato City', NULL, NOW()),
  ('Sapalan ES', 'Cotabato City', NULL, NOW()),
  ('Sibuto ES', 'Cotabato City', NULL, NOW()),
  ('Tenonggos Elementary School', 'Cotabato City', NULL, NOW()),
  ('Bagumbayan ES', 'Cotabato City', NULL, NOW()),
  ('Balong ES', 'Cotabato City', NULL, NOW()),
  ('Dadtumeg ES', 'Cotabato City', NULL, NOW()),
  ('Gambar ES', 'Cotabato City', NULL, NOW()),
  ('Ganta PS', 'Cotabato City', NULL, NOW()),
  ('Gayonga CES', 'Cotabato City', NULL, NOW()),
  ('Kabuntalan CES', 'Cotabato City', NULL, NOW()),
  ('Katidtuan ES', 'Cotabato City', NULL, NOW()),
  ('Libungan ES', 'Cotabato City', NULL, NOW()),
  ('Lower Taviran ES', 'Cotabato City', NULL, NOW()),
  ('Maitong ES', 'Cotabato City', NULL, NOW()),
  ('Manampen ES', 'Cotabato City', NULL, NOW()),
  ('Montay Elementary School', 'Cotabato City', NULL, NOW()),
  ('Pagalungan PS', 'Cotabato City', NULL, NOW()),
  ('Pananggalan PS', 'Cotabato City', NULL, NOW()),
  ('Sabaken PS', 'Cotabato City', NULL, NOW()),
  ('Taviran ES', 'Cotabato City', NULL, NOW()),
  ('Tumaguinting ES', 'Cotabato City', NULL, NOW()),
  ('Bayanga ES', 'Cotabato City', NULL, NOW()),
  ('Cabaniacawan PS', 'Cotabato City', NULL, NOW()),
  ('Cabugao ES', 'Cotabato City', NULL, NOW()),
  ('Campo I ES', 'Cotabato City', NULL, NOW()),
  ('Ibay ES', 'Cotabato City', NULL, NOW()),
  ('Katubo ES', 'Cotabato City', NULL, NOW()),
  ('Kidama PS', 'Cotabato City', NULL, NOW()),
  ('Langkong ES', 'Cotabato City', NULL, NOW()),
  ('Marantao PS', 'Cotabato City', NULL, NOW()),
  ('Matanog CES', 'Cotabato City', NULL, NOW()),
  ('Pangtoon ES', 'Cotabato City', NULL, NOW()),
  ('Pindulunan PS', 'Cotabato City', NULL, NOW()),
  ('Sultan Mandayan ES', 'Cotabato City', NULL, NOW()),
  ('Aragasi ES', 'Cotabato City', NULL, NOW()),
  ('Biruar CES', 'Cotabato City', NULL, NOW()),
  ('E. Molina Sr. Memo. ES', 'Cotabato City', NULL, NOW()),
  ('H. Asma Biruar ES', 'Cotabato City', NULL, NOW()),
  ('Kutongan ES', 'Cotabato City', NULL, NOW()),
  ('Lidasan Primary School', 'Cotabato City', NULL, NOW()),
  ('Limbayan ES', 'Cotabato City', NULL, NOW()),
  ('Macarimbang-Alegado Memo. ES', 'Cotabato City', NULL, NOW()),
  ('Macasandag Elementary School', 'Cotabato City', NULL, NOW()),
  ('Making ES', 'Cotabato City', NULL, NOW()),
  ('Miramar Elementary School', 'Cotabato City', NULL, NOW()),
  ('Parang Central Elementary School', 'Cotabato City', NULL, NOW()),
  ('Punta CES', 'Cotabato City', NULL, NOW()),
  ('Talaubang PS', 'Cotabato City', NULL, NOW()),
  ('Cabuan Elementary School', 'Cotabato City', NULL, NOW()),
  ('Guiday T. Biruar ES', 'Cotabato City', NULL, NOW()),
  ('Guinaid Guiani Mem. ES', 'Cotabato City', NULL, NOW()),
  ('Talib B. Abo ES', 'Cotabato City', NULL, NOW()),
  ('Nituan ES', 'Cotabato City', NULL, NOW()),
  ('Orandang Elementary School', 'Cotabato City', NULL, NOW()),
  ('Saliguidan Mem. ES', 'Cotabato City', NULL, NOW()),
  ('Sagasab ES', 'Cotabato City', NULL, NOW()),
  ('Sarmiento CES', 'Cotabato City', NULL, NOW()),
  ('Sarmiento West ES', 'Cotabato City', NULL, NOW()),
  ('Timbangan ES', 'Cotabato City', NULL, NOW()),
  ('William Reed ES', 'Cotabato City', NULL, NOW()),
  ('Bulibod ES', 'Cotabato City', NULL, NOW()),
  ('Datu Manguda Mangilay ES', 'Cotabato City', NULL, NOW()),
  ('Datu Mulok ES', 'Cotabato City', NULL, NOW()),
  ('Dalumangcob PS', 'Cotabato City', NULL, NOW()),
  ('Hadji Edza Memo. ES.', 'Cotabato City', NULL, NOW()),
  ('Ibotigen ES', 'Cotabato City', NULL, NOW()),
  ('Kakar PS', 'Cotabato City', NULL, NOW()),
  ('Kapimpilan ES', 'Cotabato City', NULL, NOW()),
  ('Maguindanaon ES', 'Cotabato City', NULL, NOW()),
  ('Maidapa PS', 'Cotabato City', NULL, NOW()),
  ('Narra ES', 'Cotabato City', NULL, NOW()),
  ('Nuling CES', 'Cotabato City', NULL, NOW()),
  ('Paiguan Elementary School', 'Cotabato City', NULL, NOW()),
  ('Panatan ES', 'Cotabato City', NULL, NOW()),
  ('Pinaring ES', 'Cotabato City', NULL, NOW()),
  ('Raguisi PS', 'Cotabato City', NULL, NOW()),
  ('Rebuken ES', 'Cotabato City', NULL, NOW()),
  ('Sandakan Elementary School', 'Cotabato City', NULL, NOW()),
  ('Ungap PS', 'Cotabato City', NULL, NOW()),
  ('Alamada ES', 'Cotabato City', NULL, NOW()),
  ('Balut ES', 'Cotabato City', NULL, NOW()),
  ('Boliok Elementary School', 'Cotabato City', NULL, NOW()),
  ('Bungabong Primary School', 'Cotabato City', NULL, NOW()),
  ('Dagurungan ES', 'Cotabato City', NULL, NOW()),
  ('Ladia ES', 'Cotabato City', NULL, NOW()),
  ('Matingen PS', 'Cotabato City', NULL, NOW()),
  ('Nekitan PS', 'Cotabato City', NULL, NOW()),
  ('Pigcalagan ES', 'Cotabato City', NULL, NOW()),
  ('Pingping PS', 'Cotabato City', NULL, NOW()),
  ('Simuay Junct. CES', 'Cotabato City', NULL, NOW()),
  ('Simuay Seashore ES.', 'Cotabato City', NULL, NOW()),
  ('Datu Panda ES', 'Cotabato City', NULL, NOW()),
  ('Tambo ES', 'Cotabato City', NULL, NOW()),
  ('Tapayan CES', 'Cotabato City', NULL, NOW()),
  ('Tariken Elementary School', 'Cotabato City', NULL, NOW()),
  ('Tuka ES', 'Cotabato City', NULL, NOW()),
  ('Bintan ES', 'Cotabato City', NULL, NOW()),
  ('Datu Mapandala ES', 'Cotabato City', NULL, NOW()),
  ('Gadungan ES', 'Cotabato City', NULL, NOW()),
  ('Datu Cabile A. Sumagka Elementary School', 'Cotabato City', NULL, NOW()),
  ('Macadayon ES', 'Cotabato City', NULL, NOW()),
  ('Pageda ES', 'Cotabato City', NULL, NOW()),
  ('Talitay CES', 'Cotabato City', NULL, NOW()),
  ('Bantek ES', 'Cotabato City', NULL, NOW()),
  ('Bliugan ES', 'Cotabato City', NULL, NOW()),
  ('Blensong Elementary School', 'Cotabato City', NULL, NOW()),
  ('Bongbong Elementary School', 'Cotabato City', NULL, NOW()),
  ('Bugabungan ES', 'Cotabato City', NULL, NOW()),
  ('Borongotan ES', 'Cotabato City', NULL, NOW()),
  ('Darugao Elementary School', 'Cotabato City', NULL, NOW()),
  ('F. Besas Sr. ES', 'Cotabato City', NULL, NOW()),
  ('Fantil ES', 'Cotabato City', NULL, NOW()),
  ('Gamek ES', 'Cotabato City', NULL, NOW()),
  ('Kabakaba Elementary School', 'Cotabato City', NULL, NOW()),
  ('Kabugkabug ES', 'Cotabato City', NULL, NOW()),
  ('Kabutoyen ES', 'Cotabato City', NULL, NOW()),
  ('Kamonsawi ES', 'Cotabato City', NULL, NOW()),
  ('Kapilit ES', 'Cotabato City', NULL, NOW()),
  ('Katiguesen ES', 'Cotabato City', NULL, NOW()),
  ('Kibleg ES', 'Cotabato City', NULL, NOW()),
  ('Kindal ES', 'Cotabato City', NULL, NOW()),
  ('Mirab ES', 'Cotabato City', NULL, NOW()),
  ('Nuro CES', 'Cotabato City', NULL, NOW()),
  ('Passi ES', 'Cotabato City', NULL, NOW()),
  ('Pedro C. Dolores ES', 'Cotabato City', NULL, NOW()),
  ('Ranao Pilayan ES', 'Cotabato City', NULL, NOW()),
  ('Renti ES', 'Cotabato City', NULL, NOW()),
  ('S. Midal ES', 'Cotabato City', NULL, NOW()),
  ('Sefegefen Elementary School', 'Cotabato City', NULL, NOW()),
  ('Tenongol ES', 'Cotabato City', NULL, NOW()),
  ('Tudok Mamot Elementary School', 'Cotabato City', NULL, NOW()),
  ('Bacayawan ES', 'Cotabato City', NULL, NOW()),
  ('Blala ES', 'Cotabato City', NULL, NOW()),
  ('Datu Sa Biwang ES', 'Cotabato City', NULL, NOW()),
  ('Dawat Central Elementary School', 'Cotabato City', NULL, NOW()),
  ('Don F. Blanco, Sr. ES', 'Cotabato City', NULL, NOW()),
  ('Kiga ES', 'Cotabato City', NULL, NOW()),
  ('Kinimi Elementary School', 'Cotabato City', NULL, NOW()),
  ('Lahangkeb ES', 'Cotabato City', NULL, NOW()),
  ('Laguitan PS', 'Cotabato City', NULL, NOW()),
  ('Maningula ES', 'Cotabato City', NULL, NOW()),
  ('Meti PS', 'Cotabato City', NULL, NOW()),
  ('Nalkan ES', 'Cotabato City', NULL, NOW()),
  ('Carlos Palindac ES', 'Cotabato City', NULL, NOW()),
  ('Ranao Midafa Elementary School', 'Cotabato City', NULL, NOW()),
  ('Resa Elementary School', 'Cotabato City', NULL, NOW()),
  ('Sabaken Central ES', 'Cotabato City', NULL, NOW()),
  ('Sedem ES', 'Cotabato City', NULL, NOW()),
  ('Sinipak Elementary School', 'Cotabato City', NULL, NOW()),
  ('Tambak ES', 'Cotabato City', NULL, NOW()),
  ('Tinindanan ES', 'Cotabato City', NULL, NOW()),
  ('Tubuan ES', 'Cotabato City', NULL, NOW()),
  ('GHAZALI B. JAAFAR MEMORIAL ELEMENTARY SCHOOL', 'Cotabato City', NULL, NOW()),
  ('KAKAR ES', 'Cotabato City', NULL, NOW()),
  ('MOHAMMAD - ALI S. GURO MEMORIAL ELEMENTARY SCHOOL', 'Cotabato City', NULL, NOW()),
  ('Ampuan ES', 'Cotabato City', NULL, NOW()),
  ('Dulangan Elementary School', 'Cotabato City', NULL, NOW()),
  ('Tambak PS', 'Cotabato City', NULL, NOW()),
  ('Camp Ebrahim Sema ES', 'Cotabato City', NULL, NOW()),
  ('Pened PS', 'Cotabato City', NULL, NOW()),
  ('Katidtuan Elementary School', 'Cotabato City', NULL, NOW()),
  ('Lipawan Elementary School', 'Cotabato City', NULL, NOW()),
  ('Madalum ES', 'Cotabato City', NULL, NOW()),
  ('Senditan PS', 'Cotabato City', NULL, NOW()),
  ('Banatin PS', 'Cotabato City', NULL, NOW()),
  ('Guiawa Elementary School', 'Cotabato City', NULL, NOW()),
  ('Hadji Datu Taha Biruar PS', 'Cotabato City', NULL, NOW()),
  ('Datu Abolais A. Manalao ES', 'Cotabato City', NULL, NOW()),
  ('Caruisan PS', 'Cotabato City', NULL, NOW()),
  ('Datu Abolais Manalao ES', 'Cotabato City', NULL, NOW()),
  ('Pinadzangca PS', 'Cotabato City', NULL, NOW()),
  ('Darping Elementary School', 'Cotabato City', NULL, NOW()),
  ('Pablo Antipolo, Sr. Elementary School (Damatog PS)', 'Cotabato City', NULL, NOW()),
  ('Sultan Malambut ES', 'Cotabato City', NULL, NOW()),
  ('Butilen Elementary School', 'Cotabato City', NULL, NOW()),
  ('Langeban PS', 'Cotabato City', NULL, NOW()),
  ('Datu Butocan Abas ES', 'Cotabato City', NULL, NOW()),
  ('Lamin ES', 'Cotabato City', NULL, NOW()),
  ('Minabay ES', 'Cotabato City', NULL, NOW()),
  ('Pangambitan ES', 'Cotabato City', NULL, NOW()),
  ('Matilak ES', 'Cotabato City', NULL, NOW()),
  ('L''mbak ES', 'Cotabato City', NULL, NOW()),
  ('Tanulang Elementary School', 'Cotabato City', NULL, NOW()),
  ('Central Oring ES', 'Cotabato City', NULL, NOW()),
  ('Kirkir Elementary School', 'Cotabato City', NULL, NOW()),
  ('Namuken Elementary School', 'Cotabato City', NULL, NOW()),
  ('Kilalan ES', 'Cotabato City', NULL, NOW()),
  ('Manggay ES', 'Cotabato City', NULL, NOW()),
  ('Panggao ES', 'Cotabato City', NULL, NOW()),
  ('Lagaan PS', 'Cotabato City', NULL, NOW()),
  ('Tataya Primary School', 'Cotabato City', NULL, NOW()),
  ('Saday Elementary School', 'Cotabato City', NULL, NOW()),
  ('MUPAAT ES', 'Cotabato City', NULL, NOW()),
  ('Panasang PS', 'Cotabato City', NULL, NOW()),
  ('Tanggao Elementary School', 'Cotabato City', NULL, NOW()),
  ('Kulodan ES', 'Cotabato City', NULL, NOW()),
  ('Gadungan Pebpandaran PS', 'Cotabato City', NULL, NOW()),
  ('Dimagalen elementary school', 'Cotabato City', NULL, NOW()),
  ('Kabuluan Primary School', 'Cotabato City', NULL, NOW()),
  ('Angimbzar T. Pendatu', 'Cotabato City', NULL, NOW()),
  ('Royod Elementary School', 'Cotabato City', NULL, NOW()),
  ('Sarmiento Elementary School', 'Cotabato City', NULL, NOW()),
  ('Kibucay National High School', 'Cotabato City', NULL, NOW()),
  ('B. Gallego-Edcor NHS', 'Cotabato City', NULL, NOW()),
  ('Camp Siongco NHS', 'Cotabato City', NULL, NOW()),
  ('Dinganen-Buldon NHS', 'Cotabato City', NULL, NOW()),
  ('Gayonga National High School', 'Cotabato City', NULL, NOW()),
  ('Kabuntalan NHS', 'Cotabato City', NULL, NOW()),
  ('Litayen National High School', 'Cotabato City', NULL, NOW()),
  ('ARMM Regional Science High School', 'Cotabato City', NULL, NOW()),
  ('Matanog NHS', 'Cotabato City', NULL, NOW()),
  ('Amir Bara Lidasan NHS', 'Cotabato City', NULL, NOW()),
  ('Parang National High School', 'Cotabato City', NULL, NOW()),
  ('Dr. Bernabe G. De La Fuente Sr. NHS', 'Cotabato City', NULL, NOW()),
  ('Sarilikha HS', 'Cotabato City', NULL, NOW()),
  ('Sultan Barira NHS', 'Cotabato City', NULL, NOW()),
  ('Sultan Kudarat NHS', 'Cotabato City', NULL, NOW()),
  ('Camp Ebrahim Sema National High School', 'Cotabato City', NULL, NOW()),
  ('BENJAMIN Q. JOSEPH NATIONAL HIGH SCHOOL', 'Cotabato City', NULL, NOW()),
  ('GADUNG NATIONAL HIGH SCHOOL', 'Cotabato City', NULL, NOW()),
  ('Datu Usngan S. Mastura NHS', 'Cotabato City', NULL, NOW()),
  ('Karim NHS', 'Cotabato City', NULL, NOW()),
  ('Sultan Mastura NHS', 'Cotabato City', NULL, NOW()),
  ('Talitay NHS', 'Cotabato City', NULL, NOW()),
  ('Datu Arnel Datukon NHS', 'Cotabato City', NULL, NOW()),
  ('Bugabungan NHS', 'Cotabato City', NULL, NOW()),
  ('Ruth Manion Babao Mem. NHS', 'Cotabato City', NULL, NOW()),
  ('Datu Alamanza Dilangalen NHS', 'Cotabato City', NULL, NOW()),
  ('Nuling National High School', 'Cotabato City', NULL, NOW()),
  ('Sabaken National High School', 'Cotabato City', NULL, NOW()),
  ('Datu Alamada Memorial NHS', 'Cotabato City', NULL, NOW()),
  ('DULANGAN NATIONAL HIGH SCHOOL', 'Cotabato City', NULL, NOW()),
  ('Nangi National High School', 'Cotabato City', NULL, NOW()),
  ('Upi Agricultural School', 'Cotabato City', NULL, NOW()),
  ('Datu Malambut NHS', 'Cotabato City', NULL, NOW()),
  ('Bai Hanina S. Sinsuat NHS', 'Cotabato City', NULL, NOW()),
  ('Making Integrated Vocational & Technology High School', 'Cotabato City', NULL, NOW()),
  ('Ibay NHS', 'Cotabato City', NULL, NOW()),
  ('Samad Sumail NHS', 'Cotabato City', NULL, NOW()),
  ('Ibrahim B. Tomawis NHS', 'Cotabato City', NULL, NOW()),
  ('Sulon National High School', 'Cotabato City', NULL, NOW()),
  ('Datu Mantato National High School', 'Cotabato City', NULL, NOW()),
  ('Camp Darapanan Integrated School', 'Cotabato City', NULL, NOW()),
  ('Datu Mohammad A. Sinsuat, Sr. Integrated School', 'Cotabato City', NULL, NOW()),
  ('School Name', 'Cotabato City', NULL, NOW()),
  ('Datu Pendatun Abas Elementary School', 'Cotabato City', NULL, NOW()),
  ('Dungguan ES', 'Cotabato City', NULL, NOW()),
  ('Sulok Elementary School', 'Cotabato City', NULL, NOW()),
  ('Tapodoc ES', 'Cotabato City', NULL, NOW()),
  ('Pebpoloan ES', 'Cotabato City', NULL, NOW()),
  ('Kibayao ES', 'Cotabato City', NULL, NOW()),
  ('Kitulaan ES', 'Cotabato City', NULL, NOW()),
  ('Langogan Elementary School', 'Cotabato City', NULL, NOW()),
  ('Manarapan ES', 'Cotabato City', NULL, NOW()),
  ('Nasapian ES', 'Cotabato City', NULL, NOW()),
  ('Tupig Elementary School', 'Cotabato City', NULL, NOW()),
  ('Sanggadong ES', 'Cotabato City', NULL, NOW()),
  ('Buluan ES', 'Cotabato City', NULL, NOW()),
  ('Pedtad ES (Mulao)', 'Cotabato City', NULL, NOW()),
  ('Nangaan ES', 'Cotabato City', NULL, NOW()),
  ('Siento Trenta ES', 'Cotabato City', NULL, NOW()),
  ('Simbuhay ES', 'Cotabato City', NULL, NOW()),
  ('Simone ES', 'Cotabato City', NULL, NOW()),
  ('Tamped ES', 'Cotabato City', NULL, NOW()),
  ('Madendog ES', 'Cotabato City', NULL, NOW()),
  ('D. D. Dilangalen ES', 'Cotabato City', NULL, NOW()),
  ('Don Miguel Latada ES', 'Cotabato City', NULL, NOW()),
  ('Damatulan ES', 'Cotabato City', NULL, NOW()),
  ('Kadigasan ES', 'Cotabato City', NULL, NOW()),
  ('Endaila Silongan Central Elementary School', 'Cotabato City', NULL, NOW()),
  ('Kudarangan ES', 'Cotabato City', NULL, NOW()),
  ('Hadji Ungkakay ES (Lower Olandang ES)', 'Cotabato City', NULL, NOW()),
  ('Malingao Elementary School', 'Cotabato City', NULL, NOW()),
  ('Mudseng ES', 'Cotabato City', NULL, NOW()),
  ('Nabalawag ES', 'Cotabato City', NULL, NOW()),
  ('Akmad Elementary School', 'Cotabato City', NULL, NOW()),
  ('Sambulawan ES', 'Cotabato City', NULL, NOW()),
  ('Datu Guilem Piang Elementary School', 'Cotabato City', NULL, NOW()),
  ('Patot ES', 'Cotabato City', NULL, NOW()),
  ('Balacayon Elementary School', 'Cotabato City', NULL, NOW()),
  ('Buricain Elementary School', 'Cotabato City', NULL, NOW()),
  ('Datu Binasing ES', 'Cotabato City', NULL, NOW()),
  ('KADINGILAN ELEMENTARY SCHOOL', 'Cotabato City', NULL, NOW()),
  ('Libungan Torreta Elementary School', 'Cotabato City', NULL, NOW()),
  ('Lower Pangangcalan Elementary School', 'Cotabato City', NULL, NOW()),
  ('MATILAC ES', 'Cotabato City', NULL, NOW()),
  ('Simsiman CES', 'Cotabato City', NULL, NOW()),
  ('Upper Pangangcalan ES', 'Cotabato City', NULL, NOW()),
  ('Balongis ES', 'Cotabato City', NULL, NOW()),
  ('Batulawan Central ES', 'Cotabato City', NULL, NOW()),
  ('Ganasi ES', 'Cotabato City', NULL, NOW()),
  ('Gokotan ES', 'Cotabato City', NULL, NOW()),
  ('Nabundas ES', 'Cotabato City', NULL, NOW()),
  ('Nalapaan Elementary School', 'Cotabato City', NULL, NOW()),
  ('Panicupan ES', 'Cotabato City', NULL, NOW()),
  ('Bagoinged ES', 'Cotabato City', NULL, NOW()),
  ('Barungis ES', 'Cotabato City', NULL, NOW()),
  ('Buliok Elementary School', 'Cotabato City', NULL, NOW()),
  ('Bulol Elementary School', 'Cotabato City', NULL, NOW()),
  ('Fort Pikit ES', 'Cotabato City', NULL, NOW()),
  ('Gligli ES', 'Cotabato City', NULL, NOW()),
  ('Kabasalan ES', 'Cotabato City', NULL, NOW()),
  ('Rajah Muda ES', 'Cotabato City', NULL, NOW()),
  ('Balong ES', 'Cotabato City', NULL, NOW()),
  ('Binandal PS', 'Cotabato City', NULL, NOW()),
  ('Bualan ES', 'Cotabato City', NULL, NOW()),
  ('Lagunde ES', 'Cotabato City', NULL, NOW()),
  ('Macabual ES', 'Cotabato City', NULL, NOW()),
  ('Dulangan M. Abid ES', 'Cotabato City', NULL, NOW()),
  ('Manaulanan ES', 'Cotabato City', NULL, NOW()),
  ('Pamalian ES', 'Cotabato City', NULL, NOW()),
  ('Dalimbang Elementary School', 'Cotabato City', NULL, NOW()),
  ('AL-ASIM ELEMENTARY SCHOOL', 'Cotabato City', NULL, NOW()),
  ('Mongkas Elementary School', 'Cotabato City', NULL, NOW()),
  ('Datu Tumindeg Sultan Island Elementary School', 'Cotabato City', NULL, NOW()),
  ('SAYUGAN PRIMARY SCHOOL', 'Cotabato City', NULL, NOW()),
  ('PANTADEN PRIMARY SCHOOL', 'Cotabato City', NULL, NOW()),
  ('Guntong ES', 'Cotabato City', NULL, NOW()),
  ('Nunguan ES', 'Cotabato City', NULL, NOW()),
  ('Lower Baguer Elementry School', 'Cotabato City', NULL, NOW()),
  ('Dabpil Sampulna ES', 'Cotabato City', NULL, NOW()),
  ('Balibet ES', 'Cotabato City', NULL, NOW()),
  ('Datu Mantil ES', 'Cotabato City', NULL, NOW()),
  ('DILUTAN ELEMENTARY SCHOOL', 'Cotabato City', NULL, NOW()),
  ('Mulita Elementary School', 'Cotabato City', NULL, NOW()),
  ('Dangleg Elementary School', 'Cotabato City', NULL, NOW()),
  ('Edol Daud Mem. ES', 'Cotabato City', NULL, NOW()),
  ('Malik Mem. ES', 'Cotabato City', NULL, NOW()),
  ('Pandita ES', 'Cotabato City', NULL, NOW()),
  ('Dimanalao ES', 'Cotabato City', NULL, NOW()),
  ('Dagadas Elementary School', 'Cotabato City', NULL, NOW()),
  ('Datu Tumindeg Sultan Memorial E.S.', 'Cotabato City', NULL, NOW()),
  ('Bai Monerah Abas Asim High School', 'Cotabato City', NULL, NOW()),
  ('Kibayao High School', 'Cotabato City', NULL, NOW()),
  ('Carmen NHS - Kitulaan Annex', 'Cotabato City', NULL, NOW()),
  ('Matilac HS', 'Cotabato City', NULL, NOW()),
  ('Olandang NHS', 'Cotabato City', NULL, NOW()),
  ('Rajah Muda National High School', 'Cotabato City', NULL, NOW()),
  ('Kapinpilan High School', 'Cotabato City', NULL, NOW()),
  ('Simsiman HS', 'Cotabato City', NULL, NOW()),
  ('PEBPOLOAN HIGH SCHOOL', 'Cotabato City', NULL, NOW()),
  ('Balong High School', 'Cotabato City', NULL, NOW()),
  ('Panicupan High School', 'Cotabato City', NULL, NOW()),
  ('DATU TUMINDEG SULTAN ISLAND HIGH SCHOOL', 'Cotabato City', NULL, NOW()),
  ('DATU TUMINDEG SULTAN HIGH SCHOOL', 'Cotabato City', NULL, NOW()),
  ('TAMPED HIGH SCHOOL', 'Cotabato City', NULL, NOW()),
  ('Kabasalan High School', 'Cotabato City', NULL, NOW()),
  ('MALINGAO HIGH SCHOOL', 'Cotabato City', NULL, NOW()),
  ('DUNGUAN-MATANOG HIGH SCHOOL', 'Cotabato City', NULL, NOW()),
  ('TUPIG HIGH SCHOOL', 'Cotabato City', NULL, NOW()),
  ('Pigcawayan NHS - Patot Annex', 'Cotabato City', NULL, NOW()),
  ('Pikit NHS - Balongis Annex', 'Cotabato City', NULL, NOW()),
  ('Pikit NHS - Gokotan Annex', 'Cotabato City', NULL, NOW()),
  ('Nangaan High School', 'Cotabato City', NULL, NOW()),
  ('Datu Daud Rahman High School', 'Cotabato City', NULL, NOW()),
  ('BULOL HIGH SCHOOL', 'Cotabato City', NULL, NOW()),
  ('Salunayan HS - Nabalawag HS Annex', 'Cotabato City', NULL, NOW()),
  ('Salunayan NHS-Dabpil Sampulna Olandang HS Annex', 'Cotabato City', NULL, NOW()),
  ('Manuangan HS-Datu Binasing HS Annex', 'Cotabato City', NULL, NOW()),
  ('Datu Embak Mangansing Memorial High School', 'Cotabato City', NULL, NOW()),
  ('Simone HS', 'Cotabato City', NULL, NOW())
ON CONFLICT DO NOTHING;

-- Verify import
SELECT COUNT(*) as total_schools FROM schools;
