import { useState, useEffect } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { CheckCircle2, Copy, Download, Home } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface RegistrationSuccessDialogProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    scoutId: string;
    scoutName: string;
    onGoHome: () => void;
    autoRedirectDelay?: number; // Delay in seconds before auto-redirect
}

export function RegistrationSuccessDialog({
    open,
    onOpenChange,
    scoutId,
    scoutName,
    onGoHome,
    autoRedirectDelay = 5, // Default 5 seconds
}: RegistrationSuccessDialogProps) {
    const { toast } = useToast();
    const [countdown, setCountdown] = useState(autoRedirectDelay);

    // Reset countdown when dialog opens
    useEffect(() => {
        if (open) {
            setCountdown(autoRedirectDelay);
        }
    }, [open, autoRedirectDelay]);

    // Countdown timer and auto-redirect
    useEffect(() => {
        if (!open) return;

        if (countdown <= 0) {
            onGoHome();
            return;
        }

        const timer = setTimeout(() => {
            setCountdown(prev => prev - 1);
        }, 1000);

        return () => clearTimeout(timer);
    }, [open, countdown, onGoHome]);

    const handleCopyId = async () => {
        try {
            await navigator.clipboard.writeText(scoutId);
            toast({
                title: "Copied!",
                description: "Scout ID copied to clipboard",
            });
        } catch (error) {
            toast({
                title: "Failed to copy",
                description: "Please manually select and copy the ID",
                variant: "destructive",
            });
        }
    };

    const handleDownload = () => {
        const content = `
=====================================
    BOY SCOUTS OF THE PHILIPPINES
        SCOUT REGISTRATION
=====================================

Congratulations, ${scoutName}!

Your registration has been submitted successfully.

SCOUT ID: ${scoutId}

IMPORTANT: Please keep this ID safe!
You will need it to:
- Sign in to your account
- Verify your identity
- Access your scout profile

Your registration is currently PENDING.
An administrator will review and approve
your registration soon.

=====================================
        Generated by ScoutSmart
=====================================
    `.trim();

        const blob = new Blob([content], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `ScoutID_${scoutId}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);

        toast({
            title: "Downloaded!",
            description: "Scout ID file has been downloaded",
        });
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="max-w-md">
                <DialogHeader className="text-center">
                    <div className="flex justify-center mb-4">
                        <div className="h-16 w-16 bg-green-100 dark:bg-green-900/30 rounded-full flex items-center justify-center">
                            <CheckCircle2 className="h-10 w-10 text-green-600 dark:text-green-400" />
                        </div>
                    </div>
                    <DialogTitle className="text-2xl text-center">Registration Successful!</DialogTitle>
                    <DialogDescription className="text-center">
                        Congratulations, {scoutName}! Your registration has been submitted.
                    </DialogDescription>
                </DialogHeader>

                <div className="space-y-4 py-4">
                    {/* Scout ID Display */}
                    <div className="bg-muted rounded-lg p-4 text-center">
                        <p className="text-sm text-muted-foreground mb-2">Your Scout ID</p>
                        <p className="text-2xl font-mono font-bold text-primary select-all">
                            {scoutId}
                        </p>
                    </div>

                    {/* Warning */}
                    <div className="bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800 rounded-lg p-3">
                        <p className="text-sm text-amber-800 dark:text-amber-200">
                            <strong>Important:</strong> Please save this ID - you'll need it to sign in to your account.
                            Your registration is pending admin approval.
                        </p>
                    </div>

                    {/* Action Buttons */}
                    <div className="flex gap-2">
                        <Button
                            variant="outline"
                            className="flex-1"
                            onClick={handleCopyId}
                        >
                            <Copy className="h-4 w-4 mr-2" />
                            Copy ID
                        </Button>
                        <Button
                            variant="outline"
                            className="flex-1"
                            onClick={handleDownload}
                        >
                            <Download className="h-4 w-4 mr-2" />
                            Download
                        </Button>
                    </div>
                </div>

                <DialogFooter className="flex-col gap-2">
                    {/* Countdown notice */}
                    <p className="text-sm text-muted-foreground text-center">
                        Redirecting to homepage in <span className="font-bold text-primary">{countdown}</span> seconds...
                    </p>
                    <Button
                        className="w-full"
                        onClick={onGoHome}
                    >
                        <Home className="h-4 w-4 mr-2" />
                        Go to Homepage Now
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
